<?php

/**
 * @file
 * Contains sayan_qr.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\block\Entity\Block;

/**
 * Implements hook_help().
 */
function sayan_qr_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the sayan_qr module.
    case 'help.page.sayan_qr':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Module for Products and QR code') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function sayan_qr_theme() {
  return [
  'sayan_qr' => [
  'render element' => 'children',
  ],

  'page__products' => [
  'template' => 'page--products',
  'base hook' => 'page'
      ],
    ];
}
function sayan_qr_theme_suggestions_page_alter(array &$suggestions, array $variables, $hook) {


  // Try to get the node, so we can check if we're on the node page.
  $node = Drupal::request()->attributes->get('node');
  if ($node && $node->getType() == 'products') {
    $suggestions[] = 'page__products';
  }
}
function sayan_qr_preprocess_page(&$variables) {


  $block_manager = \Drupal::service('plugin.manager.block');
// You can hard code configuration or you load from settings.
$config = [];
$plugin_block = $block_manager->createInstance('qrcode', $config);
// Some blocks might implement access check.
$access_result = $plugin_block->access(\Drupal::currentUser());
// Return empty render array if user doesn't have access.
// $access_result can be boolean or an AccessResult class
if (is_object($access_result) && $access_result->isForbidden() || is_bool($access_result) && !$access_result) {
  // You might need to add some cache tags/contexts.
  return [];
}
$render = $plugin_block->build();

  /* $node = Drupal::request()->attributes->get('node');
  if ($node && $node->getType() == 'products') {
  	$my_block = \Drupal\block\Entity\Block::load('qrcode');
  	$my_block_view = \Drupal::entityTypeManager()
    ->getViewBuilder('block')
    ->view($my_block);
  if ($my_block_view) { */
    $variables['page']['sidebar_second']['my_block'] = $render;
  //}
 // }

}

